### ISSUE TITLE
agvs_sim kinetic joint_states not published

### ISSUE THREAD

**Issue by MrYelameli** [RobotnikAutomation/agvs_sim#3]
I have been trying to run agvs_sim tutorials in kinetic version .http://wiki.ros.org/agvs_sim/tutorials For the following command roslaunch agvs_robot_control agvs_robot_control.launch

I am getting the following response.

AGVSControllerClass::starting

It is continous in loop.

After investigating,

rostopic echo /agvs/joint_state we found the following warning message

WARNING: no messages received and simulated time is active. Is /clock being published?

What would be the issue?

**Comment by buntyke** [comment]
I have faced a similar issue with indigo as well. On reviewing the code, we found that agvs_robot_control node is not able to get the robot state from /agvs/joint_states topic and is not able to initialize.

Could the maintainers please comment on this problem?

**Comment by CallumQuin** [comment]
I am facing the same issue as above currently. Just wondering if anyone found the solution in order to fix this problem?

Thanks
